# Site settings
author: Ramandip Rai
title: My Data Science journey with Flatiron School
header-img: img/home-bg.png
email: ramandiprai_@hotmail.co.uk
copyright_name: Ramandip Rai
description: > # this means to ignore newlines until "baseurl:"
  Sharing my learning experiences as a beginner learning to code. 
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  ramandiprai

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
